env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
plugins:
    - async-await
rules:
  async-await/space-after-async:
    - warn 
  async-await/space-after-await:
    - warn
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
